apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-api
  labels:
    driveby.io/version: "2.0.0"
    app: broken-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-api
  template:
    metadata:
      labels:
    driveby.io/version: "2.0.0"
        app: broken-api
    spec:
      containers:
        - name: api
          image: ghcr.io/novelcore/broken-api:a0ecfc5c4172385798062682b236276c758c29b4
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              value: "driveby-test-key-2024"
          livenessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /test/health
              port: 8000
            initialDelaySeconds: 3
      imagePullSecrets:
        - name: ghcr-creds
